import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
// USER PROFILE
export const themeColorOptions = [
    { value: "#F7870E" },
    { value: "#DA3B01" },
    { value: "#C239B3" },
    { value: "#0078D4" },
    { value: "#6B69D6" },
    { value: "#0099BC" },
    { value: "#018574" },
];
export const userRolesOptions = [
    { value: "ADMIN", label: "Admin" },
    { value: "SALESMANAGER", label: "Sales Manager" },
    { value: "SALESPERSON", label: "Sales Person" },
];
export const userRolesOptionsToInvite = [
    { value: "SALESMANAGER", label: "Sales Manager" },
    { value: "SALESPERSON", label: "Sales Person" },
];
export const statusValuesArray = [
    { value: "New", label: "New" },
    { value: "In Progress", label: "In Progress" },
    { value: "Qualified", label: "Qualified" },
    { value: "Closed", label: "Closed" },
];
export const ratingValuesArray = [
    { value: "Cold", label: "Cold" },
    { value: "Warm", label: "Warm" },
    { value: "Hot", label: "Hot" },
];
export const projectStatusValuesArray = [
    { value: "Ongoing", label: "Ongoing" },
    { value: "Completed", label: "Completed" },
];
export const leadsViewArray = [
    { value: "LIST", label: "List" },
    { value: "KANBAN", label: "Kanban" },
];
export const csvInstructionsCollapseItem = [
    {
        key: "1",
        label: "Instructions",
        children: (_jsxs("p", { children: ["1. Download the sample CSV file. ", _jsx("br", {}), "2. Fill in the CSV file with your product details. ", _jsx("br", {}), " 3. Upload or Drag and Drop the CSV file. ", _jsx("br", {}), " 4. Wait for the upload to finish.", " ", _jsx("br", {}), " 5. Click on the \"View Uploaded Products\" button to view your uploaded products."] })),
    },
];
export const leadSourceOptions = [
    { value: "Company Website", label: "Company Website" },
    { value: "LinkedIn", label: "LinkedIn" },
    { value: "Social Media Platforms", label: "Social Media Platforms" },
    { value: "Content Marketing", label: "Content Marketing" },
    { value: "Referrals", label: "Referrals" },
    { value: "Networking Events", label: "Networking Events" },
    {
        value: "Partnerships and Collaborations",
        label: "Partnerships and Collaborations",
    },
    {
        value: "Customer Reviews and Testimonials",
        label: "Customer Reviews and Testimonials",
    },
];
export const leadsRelatedViewOptions = [
    { value: "SELECT", label: "select related view" },
    { value: "ACTIVITIES", label: "Activities" },
    { value: "NOTES", label: "Notes" },
];
// ACCOUNTS
export const industryTypeValuesArray = [
    { value: "Select", label: "Select Industry" },
    { value: "Information Technology", label: "Information Technology" },
    { value: "Finance", label: "Finance" },
    { value: "Medical", label: "Medical" },
    { value: "Software", label: "Software" },
    { value: "Education", label: "Education" },
    { value: "Textile", label: "Textile" },
    { value: "Construction", label: "Construction" },
    { value: "Advertising", label: "Advertising" },
    {
        value: "",
        label: "Other",
    },
];
export const nameInitialTypeValuesArray = [
    { value: "Mr", label: "Mr." },
    { value: "Mrs", label: "Mrs." },
    { value: "Miss", label: "Miss" },
];
export const industryUserInfoTypeValuesArray = [
    { value: "Real Estate", label: "Real Estate" },
    { value: "Freelancer", label: "Freelancer" },
    { value: "Consulting", label: "Consulting" },
    { value: "Sales", label: "Sales" },
];
export const userRoleTypeValuesArray = [
    { value: "SALESMANAGER", label: "Sales Manager" },
    { value: "SALESPERSON", label: "Sales Person" },
];
export const accountTypeValuesArray = [
    { value: "Active", label: "Active" },
    { value: "Inactive", label: "Inactive" },
];
export const accountsRelatedViewOptions = [
    { value: "SELECT", label: "Select Related Records" },
    { value: "LEADS", label: "Leads" },
    { value: "OPPORTUNITIES", label: "Opportunities" },
    { value: "CONTACTS", label: "Contacts" },
    { value: "ACTIVITIES", label: "Activities" },
    { value: "NOTES", label: "Notes" },
];
export const activitiesRelatedViewOptions = [
    { value: "SELECT", label: "select related view" },
    { value: "NOTES", label: "Notes" },
];
export const currencyOptions = [
    { value: "INR", label: "INR" },
    { value: "GBP", label: "GBP" },
    { value: "USD", label: "USD" },
    { value: "EUR", label: "EUR" },
    { value: "AUD", label: "AUD" },
];
export const accountBusinessTypesOptions = [
    { value: "Analyst", label: "Analyst" },
    { value: "Competitor", label: "Competitor" },
    { value: "Investor", label: "Investor" },
    { value: "Partner", label: "Partner" },
    { value: "Customer", label: "Customer" },
    { value: "Integrator", label: "Integrator" },
    { value: "Reseller", label: "Reseller" },
    { value: "Prospect", label: "Prospect" },
];
// CONTACTS
export const contactTypesOptions = [
    { value: "Professional", label: "Professional" },
    { value: "Investor", label: "Investor" },
    { value: "Partner", label: "Partner" },
    { value: "Customer", label: "Customer" },
    { value: "Prospect", label: "Prospect" },
    { value: "Busineess Owner", label: "Busineess Owner" },
];
export const yesOrNo = [
    { value: "Yes", label: "Yes" },
    { value: "No", label: "No" },
];
export const countryFlags = [
    { key: "+93", value: "https://flagcdn.com/af.svg", label: "Afghanistan" },
    { key: "+358", value: "https://flagcdn.com/ax.svg", label: "Åland Islands" },
    { key: "+355", value: "https://flagcdn.com/al.svg", label: "Albania" },
    { key: "+213", value: "https://flagcdn.com/dz.svg", label: "Algeria" },
    {
        key: "+1-684",
        value: "https://flagcdn.com/as.svg",
        label: "American Samoa",
    },
    { key: "+376", value: "https://flagcdn.com/ad.svg", label: "Andorra" },
    { key: "+244", value: "https://flagcdn.com/ao.svg", label: "Angola" },
    { key: "+1-264", value: "https://flagcdn.com/ai.svg", label: "Anguilla" },
    { key: "", value: "", label: "Antarctica" },
    {
        key: "+1-268",
        value: "https://flagcdn.com/ag.svg",
        label: "Antigua and Barbuda",
    },
    { key: "+54", value: "https://flagcdn.com/ar.svg", label: "Argentina" },
    { key: "+374", value: "https://flagcdn.com/am.svg", label: "Armenia" },
    { key: "+297", value: "https://flagcdn.com/aw.svg", label: "Aruba" },
    { key: "+61", value: "https://flagcdn.com/au.svg", label: "Australia" },
    { key: "+43", value: "https://flagcdn.com/at.svg", label: "Austria" },
    { key: "+994", value: "https://flagcdn.com/az.svg", label: "Azerbaijan" },
    { key: "+1-242", value: "https://flagcdn.com/bs.svg", label: "Bahamas" },
    { key: "+973", value: "https://flagcdn.com/bh.svg", label: "Bahrain" },
    { key: "+880", value: "https://flagcdn.com/bd.svg", label: "Bangladesh" },
    { key: "+1-246", value: "https://flagcdn.com/bb.svg", label: "Barbados" },
    { key: "+375", value: "https://flagcdn.com/by.svg", label: "Belarus" },
    { key: "+32", value: "https://flagcdn.com/be.svg", label: "Belgium" },
    { key: "+501", value: "https://flagcdn.com/bz.svg", label: "Belize" },
    { key: "+229", value: "https://flagcdn.com/bj.svg", label: "Benin" },
    { key: "+1-441", value: "https://flagcdn.com/bm.svg", label: "Bermuda" },
    { key: "+975", value: "https://flagcdn.com/bt.svg", label: "Bhutan" },
    { key: "+591", value: "https://flagcdn.com/bo.svg", label: "Bolivia" },
    {
        key: "+387",
        value: "https://flagcdn.com/ba.svg",
        label: "Bosnia and Herzegovina",
    },
    { key: "+267", value: "https://flagcdn.com/bw.svg", label: "Botswana" },
    { key: "+55", value: "https://flagcdn.com/br.svg", label: "Brazil" },
    { key: "+673", value: "https://flagcdn.com/bn.svg", label: "Brunei" },
    { key: "+359", value: "https://flagcdn.com/bg.svg", label: "Bulgaria" },
    { key: "+226", value: "https://flagcdn.com/bf.svg", label: "Burkina Faso" },
    { key: "+257", value: "https://flagcdn.com/bi.svg", label: "Burundi" },
    { key: "+855", value: "https://flagcdn.com/kh.svg", label: "Cambodia" },
    { key: "+237", value: "https://flagcdn.com/cm.svg", label: "Cameroon" },
    { key: "+1", value: "https://flagcdn.com/ca.svg", label: "Canada" },
    { key: "+238", value: "https://flagcdn.com/cv.svg", label: "Cape Verde" },
    {
        key: "+1-345",
        value: "https://flagcdn.com/ky.svg",
        label: "Cayman Islands",
    },
    {
        key: "+236",
        value: "https://flagcdn.com/cf.svg",
        label: "Central African Republic",
    },
    { key: "+235", value: "https://flagcdn.com/td.svg", label: "Chad" },
    { key: "+56", value: "https://flagcdn.com/cl.svg", label: "Chile" },
    { key: "+86", value: "https://flagcdn.com/cn.svg", label: "China" },
    { key: "", value: "", label: "Christmas Island" },
    {
        key: "+61",
        value: "https://flagcdn.com/cc.svg",
        label: "Cocos (Keeling) Islands",
    },
    { key: "+57", value: "https://flagcdn.com/co.svg", label: "Colombia" },
    { key: "+269", value: "https://flagcdn.com/km.svg", label: "Comoros" },
    { key: "+242", value: "https://flagcdn.com/cg.svg", label: "Congo" },
    {
        key: "+243",
        value: "https://flagcdn.com/cd.svg",
        label: "Congo, Democratic Republic of the",
    },
    { key: "+682", value: "https://flagcdn.com/ck.svg", label: "Cook Islands" },
    { key: "+506", value: "https://flagcdn.com/cr.svg", label: "Costa Rica" },
    { key: "+225", value: "https://flagcdn.com/ci.svg", label: "Ivory Coast" },
    { key: "+385", value: "https://flagcdn.com/hr.svg", label: "Croatia" },
    { key: "+53", value: "https://flagcdn.com/cu.svg", label: "Cuba" },
    { key: "+357", value: "https://flagcdn.com/cy.svg", label: "Cyprus" },
    { key: "+420", value: "https://flagcdn.com/cz.svg", label: "Czech Republic" },
    { key: "+45", value: "https://flagcdn.com/dk.svg", label: "Denmark" },
    { key: "+253", value: "https://flagcdn.com/dj.svg", label: "Djibouti" },
    { key: "+1-767", value: "https://flagcdn.com/dm.svg", label: "Dominica" },
    {
        key: "+1-809",
        value: "https://flagcdn.com/do.svg",
        label: "Dominican Republic",
    },
    {
        key: "+1-829",
        value: "https://flagcdn.com/do.svg",
        label: "Dominican Republic",
    },
    {
        key: "+1-849",
        value: "https://flagcdn.com/do.svg",
        label: "Dominican Republic",
    },
    { key: "+593", value: "https://flagcdn.com/ec.svg", label: "Ecuador" },
    { key: "+20", value: "https://flagcdn.com/eg.svg", label: "Egypt" },
    { key: "+503", value: "https://flagcdn.com/sv.svg", label: "El Salvador" },
    { key: "", value: "", label: "England" },
    {
        key: "+240",
        value: "https://flagcdn.com/gq.svg",
        label: "Equatorial Guinea",
    },
    { key: "+291", value: "https://flagcdn.com/er.svg", label: "Eritrea" },
    { key: "+372", value: "https://flagcdn.com/ee.svg", label: "Estonia" },
    { key: "+251", value: "https://flagcdn.com/et.svg", label: "Ethiopia" },
    {
        key: "+500",
        value: "https://flagcdn.com/fk.svg",
        label: "Falkland Islands (Malvinas)",
    },
    { key: "+298", value: "https://flagcdn.com/fo.svg", label: "Faroe Islands" },
    { key: "+679", value: "https://flagcdn.com/fj.svg", label: "Fiji" },
    { key: "+358", value: "https://flagcdn.com/fi.svg", label: "Finland" },
    { key: "+33", value: "https://flagcdn.com/fr.svg", label: "France" },
    { key: "+594", value: "https://flagcdn.com/gf.svg", label: "French Guiana" },
    {
        key: "+689",
        value: "https://flagcdn.com/pf.svg",
        label: "French Polynesia",
    },
    { key: "", value: "", label: "French Southern Territories" },
    { key: "+241", value: "https://flagcdn.com/ga.svg", label: "Gabon" },
    { key: "+220", value: "https://flagcdn.com/gm.svg", label: "Gambia" },
    { key: "+995", value: "https://flagcdn.com/ge.svg", label: "Georgia" },
    { key: "+49", value: "https://flagcdn.com/de.svg", label: "Germany" },
    { key: "+233", value: "https://flagcdn.com/gh.svg", label: "Ghana" },
    { key: "+350", value: "https://flagcdn.com/gi.svg", label: "Gibraltar" },
    { key: "+30", value: "https://flagcdn.com/gr.svg", label: "Greece" },
    { key: "+299", value: "https://flagcdn.com/gl.svg", label: "Greenland" },
    { key: "+1-473", value: "https://flagcdn.com/gd.svg", label: "Grenada" },
    { key: "+590", value: "https://flagcdn.com/gp.svg", label: "Guadeloupe" },
    { key: "+1-671", value: "https://flagcdn.com/gu.svg", label: "Guam" },
    { key: "+502", value: "https://flagcdn.com/gt.svg", label: "Guatemala" },
    { key: "+44-1481", value: "https://flagcdn.com/gg.svg", label: "Guernsey" },
    { key: "+224", value: "https://flagcdn.com/gn.svg", label: "Guinea" },
    { key: "+245", value: "https://flagcdn.com/gw.svg", label: "Guinea-Bissau" },
    { key: "+592", value: "https://flagcdn.com/gy.svg", label: "Guyana" },
    { key: "+509", value: "https://flagcdn.com/ht.svg", label: "Haiti" },
    { key: "", value: "", label: "Heard Island and McDonald Islands" },
    {
        key: "+379",
        value: "https://flagcdn.com/va.svg",
        label: "Holy See (Vatican City State)",
    },
    { key: "+504", value: "https://flagcdn.com/hn.svg", label: "Honduras" },
    { key: "+852", value: "https://flagcdn.com/hk.svg", label: "Hong Kong" },
    { key: "+36", value: "https://flagcdn.com/hu.svg", label: "Hungary" },
    { key: "+354", value: "https://flagcdn.com/is.svg", label: "Iceland" },
    { key: "+91", value: "https://flagcdn.com/in.svg", label: "India" },
    { key: "+62", value: "https://flagcdn.com/id.svg", label: "Indonesia" },
    { key: "+98", value: "https://flagcdn.com/ir.svg", label: "Iran" },
    { key: "+964", value: "https://flagcdn.com/iq.svg", label: "Iraq" },
    { key: "+353", value: "https://flagcdn.com/ie.svg", label: "Ireland" },
    {
        key: "+44-1624",
        value: "https://flagcdn.com/im.svg",
        label: "Isle of Man",
    },
    { key: "+972", value: "https://flagcdn.com/il.svg", label: "Israel" },
    { key: "+39", value: "https://flagcdn.com/it.svg", label: "Italy" },
    { key: "+1-876", value: "https://flagcdn.com/jm.svg", label: "Jamaica" },
    { key: "+81", value: "https://flagcdn.com/jp.svg", label: "Japan" },
    { key: "+44-1534", value: "https://flagcdn.com/je.svg", label: "Jersey" },
    { key: "+962", value: "https://flagcdn.com/jo.svg", label: "Jordan" },
    { key: "+7", value: "https://flagcdn.com/kz.svg", label: "Kazakhstan" },
    { key: "+254", value: "https://flagcdn.com/ke.svg", label: "Kenya" },
    { key: "+686", value: "https://flagcdn.com/ki.svg", label: "Kiribati" },
    { key: "+383", value: "https://flagcdn.com/xk.svg", label: "Kosovo" },
    { key: "+965", value: "https://flagcdn.com/kw.svg", label: "Kuwait" },
    { key: "+996", value: "https://flagcdn.com/kg.svg", label: "Kyrgyzstan" },
    { key: "+856", value: "https://flagcdn.com/la.svg", label: "Laos" },
    { key: "+371", value: "https://flagcdn.com/lv.svg", label: "Latvia" },
    { key: "+961", value: "https://flagcdn.com/lb.svg", label: "Lebanon" },
    { key: "+266", value: "https://flagcdn.com/ls.svg", label: "Lesotho" },
    { key: "+231", value: "https://flagcdn.com/lr.svg", label: "Liberia" },
    { key: "+218", value: "https://flagcdn.com/ly.svg", label: "Libya" },
    { key: "+423", value: "https://flagcdn.com/li.svg", label: "Liechtenstein" },
    { key: "+370", value: "https://flagcdn.com/lt.svg", label: "Lithuania" },
    { key: "+352", value: "https://flagcdn.com/lu.svg", label: "Luxembourg" },
    { key: "+853", value: "https://flagcdn.com/mo.svg", label: "Macao" },
    {
        key: "+389",
        value: "https://flagcdn.com/mk.svg",
        label: "North Macedonia",
    },
    { key: "+261", value: "https://flagcdn.com/mg.svg", label: "Madagascar" },
    { key: "+265", value: "https://flagcdn.com/mw.svg", label: "Malawi" },
    { key: "+60", value: "https://flagcdn.com/my.svg", label: "Malaysia" },
    { key: "+960", value: "https://flagcdn.com/mv.svg", label: "Maldives" },
    { key: "+223", value: "https://flagcdn.com/ml.svg", label: "Mali" },
    { key: "+356", value: "https://flagcdn.com/mt.svg", label: "Malta" },
    {
        key: "+692",
        value: "https://flagcdn.com/mh.svg",
        label: "Marshall Islands",
    },
    { key: "+596", value: "https://flagcdn.com/mq.svg", label: "Martinique" },
    { key: "+222", value: "https://flagcdn.com/mr.svg", label: "Mauritania" },
    { key: "+230", value: "https://flagcdn.com/mu.svg", label: "Mauritius" },
    { key: "+262", value: "https://flagcdn.com/yt.svg", label: "Mayotte" },
    { key: "+52", value: "https://flagcdn.com/mx.svg", label: "Mexico" },
    { key: "+691", value: "https://flagcdn.com/fm.svg", label: "Micronesia" },
    { key: "+373", value: "https://flagcdn.com/md.svg", label: "Moldova" },
    { key: "+377", value: "https://flagcdn.com/mc.svg", label: "Monaco" },
    { key: "+976", value: "https://flagcdn.com/mn.svg", label: "Mongolia" },
    { key: "+382", value: "https://flagcdn.com/me.svg", label: "Montenegro" },
    { key: "+1-664", value: "https://flagcdn.com/ms.svg", label: "Montserrat" },
    { key: "+212", value: "https://flagcdn.com/ma.svg", label: "Morocco" },
    { key: "+258", value: "https://flagcdn.com/mz.svg", label: "Mozambique" },
    { key: "+95", value: "https://flagcdn.com/mm.svg", label: "Myanmar" },
    { key: "+264", value: "https://flagcdn.com/na.svg", label: "Namibia" },
    { key: "+674", value: "https://flagcdn.com/nr.svg", label: "Nauru" },
    { key: "+977", value: "https://flagcdn.com/np.svg", label: "Nepal" },
    { key: "+31", value: "https://flagcdn.com/nl.svg", label: "Netherlands" },
    { key: "+687", value: "https://flagcdn.com/nc.svg", label: "New Caledonia" },
    { key: "+64", value: "https://flagcdn.com/nz.svg", label: "New Zealand" },
    { key: "+505", value: "https://flagcdn.com/ni.svg", label: "Nicaragua" },
    { key: "+227", value: "https://flagcdn.com/ne.svg", label: "Niger" },
    { key: "+234", value: "https://flagcdn.com/ng.svg", label: "Nigeria" },
    { key: "+683", value: "https://flagcdn.com/nu.svg", label: "Niue" },
    { key: "+672", value: "https://flagcdn.com/nf.svg", label: "Norfolk Island" },
    { key: "+850", value: "https://flagcdn.com/kp.svg", label: "North Korea" },
    {
        key: "+1-670",
        value: "https://flagcdn.com/mp.svg",
        label: "Northern Mariana Islands",
    },
    { key: "+47", value: "https://flagcdn.com/no.svg", label: "Norway" },
    { key: "+968", value: "https://flagcdn.com/om.svg", label: "Oman" },
    { key: "+92", value: "https://flagcdn.com/pk.svg", label: "Pakistan" },
    { key: "+680", value: "https://flagcdn.com/pw.svg", label: "Palau" },
    { key: "+970", value: "https://flagcdn.com/ps.svg", label: "Palestine" },
    { key: "+507", value: "https://flagcdn.com/pa.svg", label: "Panama" },
    {
        key: "+675",
        value: "https://flagcdn.com/pg.svg",
        label: "Papua New Guinea",
    },
    { key: "+595", value: "https://flagcdn.com/py.svg", label: "Paraguay" },
    { key: "+51", value: "https://flagcdn.com/pe.svg", label: "Peru" },
    { key: "+63", value: "https://flagcdn.com/ph.svg", label: "Philippines" },
    {
        key: "+64",
        value: "https://flagcdn.com/nz.svg",
        label: "Pitcairn Islands",
    },
    { key: "+48", value: "https://flagcdn.com/pl.svg", label: "Poland" },
    { key: "+351", value: "https://flagcdn.com/pt.svg", label: "Portugal" },
    { key: "+1-787", value: "https://flagcdn.com/pr.svg", label: "Puerto Rico" },
    { key: "+1-939", value: "https://flagcdn.com/pr.svg", label: "Puerto Rico" },
    { key: "+974", value: "https://flagcdn.com/qa.svg", label: "Qatar" },
    { key: "+262", value: "https://flagcdn.com/re.svg", label: "Réunion" },
    { key: "+40", value: "https://flagcdn.com/ro.svg", label: "Romania" },
    { key: "+7", value: "https://flagcdn.com/ru.svg", label: "Russia" },
    { key: "+250", value: "https://flagcdn.com/rw.svg", label: "Rwanda" },
    { key: "+685", value: "https://flagcdn.com/ws.svg", label: "Samoa" },
    { key: "+378", value: "https://flagcdn.com/sm.svg", label: "San Marino" },
    {
        key: "+239",
        value: "https://flagcdn.com/st.svg",
        label: "São Tomé and Príncipe",
    },
    { key: "+966", value: "https://flagcdn.com/sa.svg", label: "Saudi Arabia" },
    { key: "+221", value: "https://flagcdn.com/sn.svg", label: "Senegal" },
    { key: "+381", value: "https://flagcdn.com/rs.svg", label: "Serbia" },
    { key: "+248", value: "https://flagcdn.com/sc.svg", label: "Seychelles" },
    { key: "+232", value: "https://flagcdn.com/sl.svg", label: "Sierra Leone" },
    { key: "+65", value: "https://flagcdn.com/sg.svg", label: "Singapore" },
    { key: "+421", value: "https://flagcdn.com/sk.svg", label: "Slovakia" },
    { key: "+386", value: "https://flagcdn.com/si.svg", label: "Slovenia" },
    {
        key: "+677",
        value: "https://flagcdn.com/sb.svg",
        label: "Solomon Islands",
    },
    { key: "+252", value: "https://flagcdn.com/so.svg", label: "Somalia" },
    { key: "+27", value: "https://flagcdn.com/za.svg", label: "South Africa" },
    { key: "+500", value: "https://flagcdn.com/gs.svg", label: "South Georgia" },
    { key: "+82", value: "https://flagcdn.com/kr.svg", label: "South Korea" },
    { key: "+211", value: "https://flagcdn.com/ss.svg", label: "South Sudan" },
    { key: "+34", value: "https://flagcdn.com/es.svg", label: "Spain" },
    { key: "+94", value: "https://flagcdn.com/lk.svg", label: "Sri Lanka" },
    { key: "+249", value: "https://flagcdn.com/sd.svg", label: "Sudan" },
    { key: "+597", value: "https://flagcdn.com/sr.svg", label: "Suriname" },
    {
        key: "+47",
        value: "https://flagcdn.com/sj.svg",
        label: "Svalbard and Jan Mayen",
    },
    { key: "+268", value: "https://flagcdn.com/sz.svg", label: "Eswatini" },
    { key: "+46", value: "https://flagcdn.com/se.svg", label: "Sweden" },
    { key: "+41", value: "https://flagcdn.com/ch.svg", label: "Switzerland" },
    { key: "+963", value: "https://flagcdn.com/sy.svg", label: "Syria" },
    { key: "+886", value: "https://flagcdn.com/tw.svg", label: "Taiwan" },
    { key: "+992", value: "https://flagcdn.com/tj.svg", label: "Tajikistan" },
    { key: "+255", value: "https://flagcdn.com/tz.svg", label: "Tanzania" },
    { key: "+66", value: "https://flagcdn.com/th.svg", label: "Thailand" },
    { key: "+228", value: "https://flagcdn.com/tg.svg", label: "Togo" },
    { key: "+690", value: "https://flagcdn.com/tk.svg", label: "Tokelau" },
    { key: "+676", value: "https://flagcdn.com/to.svg", label: "Tonga" },
    {
        key: "+1-868",
        value: "https://flagcdn.com/tt.svg",
        label: "Trinidad and Tobago",
    },
    { key: "+216", value: "https://flagcdn.com/tn.svg", label: "Tunisia" },
    { key: "+90", value: "https://flagcdn.com/tr.svg", label: "Turkey" },
    { key: "+993", value: "https://flagcdn.com/tm.svg", label: "Turkmenistan" },
    {
        key: "+1-649",
        value: "https://flagcdn.com/tc.svg",
        label: "Turks and Caicos Islands",
    },
    { key: "+688", value: "https://flagcdn.com/tv.svg", label: "Tuvalu" },
    { key: "+256", value: "https://flagcdn.com/ug.svg", label: "Uganda" },
    { key: "+380", value: "https://flagcdn.com/ua.svg", label: "Ukraine" },
    {
        key: "+971",
        value: "https://flagcdn.com/ae.svg",
        label: "United Arab Emirates",
    },
    { key: "+44", value: "https://flagcdn.com/gb.svg", label: "United Kingdom" },
    { key: "+1", value: "https://flagcdn.com/us.svg", label: "United States" },
    { key: "+598", value: "https://flagcdn.com/uy.svg", label: "Uruguay" },
    { key: "+998", value: "https://flagcdn.com/uz.svg", label: "Uzbekistan" },
    { key: "+678", value: "https://flagcdn.com/vu.svg", label: "Vanuatu" },
    { key: "+58", value: "https://flagcdn.com/ve.svg", label: "Venezuela" },
    { key: "+84", value: "https://flagcdn.com/vn.svg", label: "Vietnam" },
    {
        key: "+1-284",
        value: "https://flagcdn.com/vg.svg",
        label: "British Virgin Islands",
    },
    {
        key: "+1-340",
        value: "https://flagcdn.com/vi.svg",
        label: "United States Virgin Islands",
    },
    {
        key: "+681",
        value: "https://flagcdn.com/wf.svg",
        label: "Wallis and Futuna",
    },
    { key: "+212", value: "https://flagcdn.com/eh.svg", label: "Western Sahara" },
    { key: "+967", value: "https://flagcdn.com/ye.svg", label: "Yemen" },
    { key: "+260", value: "https://flagcdn.com/zm.svg", label: "Zambia" },
    { key: "+263", value: "https://flagcdn.com/zw.svg", label: "Zimbabwe" },
];
export const countryNames = [
    { value: "Afghanistan" },
    { value: "Åland Islands" },
    { value: "Albania" },
    { value: "Algeria" },
    { value: "American Samoa" },
    { value: "AndorrA" },
    { value: "Angola" },
    { value: "Anguilla" },
    { value: "Antarctica" },
    { value: "Antigua and Barbuda" },
    { value: "Argentina" },
    { value: "Armenia" },
    { value: "Aruba" },
    { value: "Australia" },
    { value: "Austria" },
    { value: "Azerbaijan" },
    { value: "Bahamas" },
    { value: "Bahrain" },
    { value: "Bangladesh" },
    { value: "Barbados" },
    { value: "Belarus" },
    { value: "Belgium" },
    { value: "Belize" },
    { value: "Benin" },
    { value: "Bermuda" },
    { value: "Bhutan" },
    { value: "Bolivia" },
    { value: "Bosnia and Herzegovina" },
    { value: "Botswana" },
    { value: "Bouvet Island" },
    { value: "Brazil" },
    { value: "British Indian Ocean Territory" },
    { value: "Brunei Darussalam" },
    { value: "Bulgaria" },
    { value: "Burkina Faso" },
    { value: "Burundi" },
    { value: "Cambodia" },
    { value: "Cameroon" },
    { value: "Canada" },
    { value: "Cape Verde" },
    { value: "Cayman Islands" },
    { value: "Central African Republic" },
    { value: "Chad" },
    { value: "Chile" },
    { value: "China" },
    { value: "Christmas Island" },
    { value: "Cocos (Keeling) Islands" },
    { value: "Colombia" },
    { value: "Comoros" },
    { value: "Congo" },
    { value: "Congo, The Democratic Republic of the" },
    { value: "Cook Islands" },
    { value: "Costa Rica" },
    { value: "Cote D'Ivoire" },
    { value: "Croatia" },
    { value: "Cuba" },
    { value: "Cyprus" },
    { value: "Czech Republic" },
    { value: "Denmark" },
    { value: "Djibouti" },
    { value: "Dominica" },
    { value: "Dominican Republic" },
    { value: "Ecuador" },
    { value: "Egypt" },
    { value: "El Salvador" },
    { value: "England" },
    { value: "Equatorial Guinea" },
    { value: "Eritrea" },
    { value: "Estonia" },
    { value: "Ethiopia" },
    { value: "Falkland Islands (Malvinas)" },
    { value: "Faroe Islands" },
    { value: "Fiji" },
    { value: "Finland" },
    { value: "France" },
    { value: "French Guiana" },
    { value: "French Polynesia" },
    { value: "French Southern Territories" },
    { value: "Gabon" },
    { value: "Gambia" },
    { value: "Georgia" },
    { value: "Germany" },
    { value: "Ghana" },
    { value: "Gibraltar" },
    { value: "Greece" },
    { value: "Greenland" },
    { value: "Grenada" },
    { value: "Guadeloupe" },
    { value: "Guam" },
    { value: "Guatemala" },
    { value: "Guernsey" },
    { value: "Guinea" },
    { value: "Guinea-Bissau" },
    { value: "Guyana" },
    { value: "Haiti" },
    { value: "Heard Island and Mcdonald Islands" },
    { value: "Holy See (Vatican City State)" },
    { value: "Honduras" },
    { value: "Hong Kong" },
    { value: "Hungary" },
    { value: "Iceland" },
    { value: "India" },
    { value: "Indonesia" },
    { value: "Iran, Islamic Republic Of" },
    { value: "Iraq" },
    { value: "Ireland" },
    { value: "Isle of Man" },
    { value: "Israel" },
    { value: "Italy" },
    { value: "Jamaica" },
    { value: "Japan" },
    { value: "Jersey" },
    { value: "Jordan" },
    { value: "Kazakhstan" },
    { value: "Kenya" },
    { value: "Kiribati" },
    { value: "Korea, Democratic People'S Republic of" },
    { value: "Korea, Republic of" },
    { value: "Kuwait" },
    { value: "Kyrgyzstan" },
    { value: "Lao People'S Democratic Republic" },
    { value: "Latvia" },
    { value: "Lebanon" },
    { value: "Lesotho" },
    { value: "Liberia" },
    { value: "Libyan Arab Jamahiriya" },
    { value: "Liechtenstein" },
    { value: "Lithuania" },
    { value: "Luxembourg" },
    { value: "Macao" },
    { value: "Macedonia, The Former Yugoslav Republic of" },
    { value: "Madagascar" },
    { value: "Malawi" },
    { value: "Malaysia" },
    { value: "Maldives" },
    { value: "Mali" },
    { value: "Malta" },
    { value: "Marshall Islands" },
    { value: "Martinique" },
    { value: "Mauritania" },
    { value: "Mauritius" },
    { value: "Mayotte" },
    { value: "Mexico" },
    { value: "Micronesia, Federated States of" },
    { value: "Moldova, Republic of" },
    { value: "Monaco" },
    { value: "Mongolia" },
    { value: "Montserrat" },
    { value: "Morocco" },
    { value: "Mozambique" },
    { value: "Myanmar" },
    { value: "Namibia" },
    { value: "Nauru" },
    { value: "Nepal" },
    { value: "Netherlands" },
    { value: "Netherlands Antilles" },
    { value: "New Caledonia" },
    { value: "New Zealand" },
    { value: "Nicaragua" },
    { value: "Niger" },
    { value: "Nigeria" },
    { value: "Niue" },
    { value: "Norfolk Island" },
    { value: "Northern Mariana Islands" },
    { value: "Norway" },
    { value: "Oman" },
    { value: "Pakistan" },
    { value: "Palau" },
    { value: "Palestinian Territory, Occupied" },
    { value: "Panama" },
    { value: "Papua New Guinea" },
    { value: "Paraguay" },
    { value: "Peru" },
    { value: "Philippines" },
    { value: "Pitcairn" },
    { value: "Poland" },
    { value: "Portugal" },
    { value: "Puerto Rico" },
    { value: "Qatar" },
    { value: "Reunion" },
    { value: "Romania" },
    { value: "Russian Federation" },
    { value: "RWANDA" },
    { value: "Samoa" },
    { value: "San Marino" },
    { value: "Sao Tome and Principe" },
    { value: "Saudi Arabia" },
    { value: "Senegal" },
    { value: "Serbia and Montenegro" },
    { value: "Seychelles" },
    { value: "Sierra Leone" },
    { value: "Singapore" },
    { value: "Slovakia" },
    { value: "Slovenia" },
    { value: "Solomon Islands" },
    { value: "Somalia" },
    { value: "South Africa" },
    { value: "South Georgia and the South Sandwich Islands" },
    { value: "Spain" },
    { value: "Sri Lanka" },
    { value: "Sudan" },
    { value: "Suriname" },
    { value: "Svalbard and Jan Mayen" },
    { value: "Swaziland" },
    { value: "Sweden" },
    { value: "Switzerland" },
    { value: "Syrian Arab Republic" },
    { value: "Taiwan, Province of China" },
    { value: "Tajikistan" },
    { value: "Tanzania, United Republic of" },
    { value: "Thailand" },
    { value: "Timor-Leste" },
    { value: "Togo" },
    { value: "Tokelau" },
    { value: "Tonga" },
    { value: "Trinidad and Tobago" },
    { value: "Tunisia" },
    { value: "Turkey" },
    { value: "Turkmenistan" },
    { value: "Turks and Caicos Islands" },
    { value: "Tuvalu" },
    { value: "Uganda" },
    { value: "Ukraine" },
    { value: "United Arab Emirates" },
    { value: "United Kingdom" },
    { value: "United States" },
    { value: "United States Minor Outlying Islands" },
    { value: "Uruguay" },
    { value: "Uzbekistan" },
    { value: "Vanuatu" },
    { value: "Venezuela" },
    { value: "Viet Nam" },
    { value: "Virgin Islands, British" },
    { value: "Virgin Islands, U.S." },
    { value: "Wallis and Futuna" },
    { value: "Western Sahara" },
    { value: "Yemen" },
    { value: "Zambia" },
    { value: "Zimbabwe" },
];
export const stateNames = [
    { value: "Andaman and Nicobar Islands" },
    { value: "Andhra Pradesh" },
    { value: "Arunachal Pradesh" },
    { value: "Assam" },
    { value: "Bihar" },
    { value: "Chandigarh" },
    { value: "Chhattisgarh" },
    { value: "Dadra and Nagar Haveli" },
    { value: "Daman and Diu" },
    { value: "Delhi" },
    { value: "Goa" },
    { value: "Gujarat" },
    { value: "Haryana" },
    { value: "Himachal Pradesh" },
    { value: "Jammu and Kashmir" },
    { value: "Jharkhand" },
    { value: "Karnataka" },
    { value: "Kerala" },
    { value: "Ladakh" },
    { value: "Lakshadweep" },
    { value: "Madhya Pradesh" },
    { value: "Maharashtra" },
    { value: "Manipur" },
    { value: "Meghalaya" },
    { value: "Mizoram" },
    { value: "Nagaland" },
    { value: "Odisha" },
    { value: "Puducherry" },
    { value: "Punjab" },
    { value: "Rajasthan" },
    { value: "Sikkim" },
    { value: "Tamil Nadu" },
    { value: "Telangana" },
    { value: "Tripura" },
    { value: "Uttar Pradesh" },
    { value: "Uttarakhand" },
    { value: "West Bengal" },
];
export const cityNames = [
    { value: "Ahmednagar" },
    { value: "Akola" },
    { value: "Amravati" },
    { value: "Aurangabad" },
    { value: "Beed" },
    { value: "Bhandara" },
    { value: "Buldhana" },
    { value: "Chandrapur" },
    { value: "Dhule" },
    { value: "Gadchiroli" },
    { value: "Gondia" },
    { value: "Hingoli" },
    { value: "Jalgaon" },
    { value: "Jalna" },
    { value: "Kolhapur" },
    { value: "Latur" },
    { value: "Mumbai City" },
    { value: "Mumbai Suburban" },
    { value: "Nagpur" },
    { value: "Nanded" },
    { value: "Nandurbar" },
    { value: "Nashik" },
    { value: "Osmanabad" },
    { value: "Palghar" },
    { value: "Parbhani" },
    { value: "Pune" },
    { value: "Raigad" },
    { value: "Ratnagiri" },
    { value: "Sangli" },
    { value: "Satara" },
    { value: "Sindhudurg" },
    { value: "Solapur" },
    { value: "Thane" },
    { value: "Wardha" },
    { value: "Washim" },
    { value: "Yavatmal" },
];
export const conactsRelatedViewOptions = [
    { value: "SELECT", label: "select related view" },
    { value: "LEADS", label: "Leads" },
    { value: "OPPORTUNITIES", label: "Opportunities" },
    { value: "ACTIVITIES", label: "Activities" },
    { value: "NOTES", label: "Notes" },
    { value: "DOCUMENTS", label: "Documents" },
];
// OPPORTUNITY
export const opporLeadStatusOptions = [
    { value: "Developed", label: "Developed" },
    { value: "Proposed", label: "Proposed" },
    { value: "Closed won", label: "Closed won" },
    { value: "Closed lost", label: "Closed lost" },
    { value: "Cancelled", label: "Cancelled" },
];
export const purchaseTimeFrameOptions = [
    { value: "1 Month", label: "1 Month" },
    { value: "2 Months", label: "2 Months" },
    { value: "3 Months", label: "3 Months" },
    { value: "4 Months", label: "4 Months" },
    { value: "5 Months", label: "5 Months" },
    { value: "6 Months", label: "6 Months" },
    { value: "7 Months", label: "7 Months" },
    { value: "8 Months", label: "8 Months" },
    { value: "9 Months", label: "9 Months" },
    { value: "10 Months", label: "10 Months" },
    { value: "11 Months", label: "11 Months" },
    { value: "12 Months", label: "12 Months" },
];
export const forecastCategoryOptions = [
    { value: "Pipeline", label: "Pipeline" },
    { value: "Best Case", label: "Best Case" },
    { value: "Committed", label: "Committed" },
    { value: "Omitted", label: "Omitted" },
    { value: "Won", label: "Won" },
    { value: "Lost", label: "Lost" },
];
export const probabilityOptions = [
    { value: "10", label: "10 %" },
    { value: "20", label: "20 %" },
    { value: "30", label: "30 %" },
    { value: "40", label: "40 %" },
    { value: "50", label: "50 %" },
    { value: "60", label: "60 %" },
    { value: "70", label: "70 %" },
    { value: "80", label: "80 %" },
    { value: "90", label: "90 %" },
    { value: "100", label: "100 %" },
];
export const stagesOptions = [
    { value: "Analysis", label: "Analysis" },
    { value: "Solutioning", label: "Solutioning" },
    { value: "Proposal", label: "Proposal" },
    { value: "Negotiation", label: "Negotiation" },
    { value: "Won", label: "Won" },
    { value: "Lost", label: "Lost" },
];
export const statusOptions = [
    { value: "Active", label: "Active" },
    { value: "Inactive", label: "Inactive" },
    { value: "Cancelled", label: "Cancelled" },
];
export const priorityOptions = [
    { value: "Low", label: "Low" },
    { value: "Medium", label: "Medium" },
    { value: "High", label: "High" },
];
export const purchaseProcessOptions = [
    { value: "Individual", label: "Individual" },
    { value: "Committee", label: "Committee" },
];
export const moodsArray = [
    { value: "HAPPY", url: "/assets/personalization/happy.svg" },
    {
        value: "NEUTRAL",
        url: "/assets/personalization/neutral.svg",
    },
    { value: "LOW", url: "/assets/personalization/sad.svg" },
];
export const opportunitiesRelatedViewOptions = [
    { value: "SELECT", label: "select related view" },
    { value: "ACTIVITIES", label: "Activities" },
    { value: "NOTES", label: "Notes" },
    { value: "DOCUMENTS", label: "Documents" },
];
export const wonReasonOptions = [
    { value: "Need Fulfilled", label: "Need Fulfilled" },
    { value: "Competitive Advantage", label: "Competitive Advantage" },
    { value: "Relationship & Trust", label: "Relationship & Trust" },
    { value: "Competitive Pricing", label: "Competitive Pricing" },
    { value: "UpSelling/CrossSelling", label: "UpSelling/CrossSelling" },
    { value: "Effective Sales Process", label: "Effective Sales Process" },
    { value: "Other", label: "Other" },
];
export const lostReasonOptions = [
    { value: "Budget Constraint", label: "Budget Constraint" },
    { value: "Competitive Selection", label: "Competitive Selection" },
    { value: "Changed Needs/Priority", label: "Changed Needs/Priority" },
    { value: "Decision Making Delay", label: "Decision Making Delay" },
    { value: "No Purchase Intent", label: "No Purchase Intent" },
    { value: "Ineffective Sales Process", label: "Ineffective Sales Process" },
    { value: "Uncompetitive Pricing", label: "Uncompetitive Pricing" },
    {
        value: "Product/Service Limitations",
        label: "Product/Service Limitations",
    },
    {
        value: "Lack of Followup or Communication",
        label: "Lack of Followup or Communication",
    },
    { value: "Other", label: "Other" },
];
// ACTIVITY
export const activityTypeOptions = [
    { value: "Task", label: "Task" },
    { value: "Meeting", label: "Meeting" },
    { value: "Documentation", label: "Documentation" },
    { value: "Data Entry", label: "Data Entry" },
    { value: "Phone Call Outbound", label: "Phone call" },
    { value: "Email Outbound", label: "Email" },
    { value: "SMS Outbound", label: "SMS" },
    { value: "Whatsapp Outbound", label: "Whatsapp" },
];
export const activityStatusOptions = [
    { value: "Open", label: "Open" },
    { value: "In Progress", label: "In Progress" },
    { value: "Completed", label: "Completed" },
];
export const activityPriorityOptions = [
    { value: "Low", label: "Low" },
    { value: "Normal", label: "Normal" },
    { value: "High", label: "High" },
];
// LEADS DASHBOARD
export const dateRangeOptions = [
    { value: "7", label: "Past 7 Days" },
    { value: "30", label: "Past 30 Days" },
    { value: "90", label: "Past 90 Days" },
    { value: "180", label: "Past 180 Days" },
    { value: "365", label: "Past 1 year" },
    {
        value: "CUSTOM_DATE",
        label: _jsx("span", { className: "hyperlinkBlue", children: "Custom Date" }),
    },
];
// REFERRALS
export const referralStatusOptions = [
    { value: "New", label: "New" },
    { value: "In Progress", label: "In Progress" },
    { value: "Closed", label: "Closed" },
];
